language: cpp
dist: xenial

branches:
  except:
    - /^appveyor.*$/

git:
  depth: 10

matrix:
  include:
    - os: windows
      env:
        - CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++"

before_install:
  - if [ -n "$GCC_VERSION" ]; then export CC="gcc-${GCC_VERSION}" CXX="g++-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CC="clang-${CLANG_VERSION}" CXX="clang++-${CLANG_VERSION}"; fi
  - $CC --version
  - $CXX --version

script:
  - echo ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - cmake -G "MSYS Makefiles" -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ ..
  #- cat CMakeFiles/CMakeOutput.log
  #- if [[ $TRAVIS_OS_NAME == 'windows' ]]; then cmake --build . -- -m; fi
  #- if [[ $TRAVIS_OS_NAME != 'windows' ]]; then cmake --build . -- -j2; fi
  - cmake --build . -- -j2 -k

notifications:
  email: false
