language: cpp
dist: xenial

branches:
  except:
    - /^appveyor.*$/

git:
  depth: 10

matrix:
  include:
    - os: windows
      env:
        - GENERATOR="MSYS Makefiles"
        - CMAKE_OPTIONS='-G "${GENERATOR}" -DCMAKE_MAKE_PROGRAM=/c/ProgramData/chocolatey/bin/make -DCMAKE_AR=/c/ProgramData/chocolatey/bin/ar'

before_install:
  - if [ -n "$GCC_VERSION" ]; then export CC="gcc-${GCC_VERSION}" CXX="g++-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CC="clang-${CLANG_VERSION}" CXX="clang++-${CLANG_VERSION}"; fi
  - $CC --version
  - $CXX --version

script:
  - echo ${TRAVIS_BUILD_DIR}
  - mkdir build
  - cd build
  - choco install make 
  - cmake ${CMAKE_OPTIONS} ..
  #- cmake --build . -- -j2 -k

notifications:
  email: false
